# Generated by Django 2.1.7 on 2019-04-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_port', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
