# Generated by Django 2.1.7 on 2019-04-04 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_port', '0004_selected'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Selected',
        ),
    ]
