# Generated by Django 2.1.7 on 2019-04-04 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_port', '0003_profile_picture'),
        ('app_port', '0005_delete_selected'),
    ]

    operations = [
    ]
